# Generated by Django 6.0.1 on 2026-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownerpermission',
            constraint=models.UniqueConstraint(fields=('owner', 'permission'), name='unique_owner_permission'),
        ),
    ]
