# Generated by Django 6.0.1 on 2026-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ownerpermission_unique_owner_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(related_name='users', through='accounts.OwnerPermission', to='accounts.permission'),
        ),
    ]
