# Generated by Django 6.0.1 on 2026-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
